# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor: !!null vim
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: cat
# Aliases allow you to create nicknames for gh commands
aliases:
    co: pr checkout
# need to run through shell (with !) to get $HOME expansion
    headless: |
      !gh api graphql -F query="@$HOME/.config/gh/project-query.gql" --template '
      {{range .data.organization.projects.nodes}}{{.name}}
      
      {{range .columns.nodes}}  {{.name}}
      
      {{range .cards.nodes}}    {{with .content}}{{.repository.nameWithOwner}}#{{.number}}: {{.title}}{{end}}
      {{end}}
      {{end}}
      {{end}}'
