#!/bin/bash

case "$1" in
'restore')
  cd ~/.config/coc/extensions/
  npm install --global-style --ignore-scripts --no-bin-links --no-package-lock --only=prod
  cd
  ;;
*)
  echo 'Supported commands: restore'
  ;;
esac
