#!/bin/bash

[ -z $BACKUP_MOUNT ] && >&2 echo 'BACKUP_MOUNT variable not set'

case "$1" in
'backup')
  echo 'Backup not supported currently'
  ;;
'restore')
  if [ ! -f "$BACKUP_MOUNT/.backup_drive" ]; then
    >&2 echo "Backup not mounted at $BACKUP_MOUNT"
    exit 1
  fi

  echo 'Copying gpg keys...'
  rclone copy --checksum --interactive $BACKUP_MOUNT/gnupg ~/.gnupg

  echo 'Copying ssh keys...'
  rclone copy --checksum --interactive $BACKUP_MOUNT/ssh ~/.ssh

  echo 'Adding ssh key to ssh-agent'
  source ~/.bashrc # to make sure ssh-agent is running
  ssh-add

  echo 'Cloning passwords with gopass'
  gopass clone ssh://git@github.com/ericselin/passwords.git
  ;;
*)
  echo 'Supported commands: backup, restore'
  ;;
esac
