#!/bin/bash

echo
echo 'Backing up: GitHub'
echo

[ -z $BACKUP_MOUNT ] && >&2 echo 'BACKUP_MOUNT not specified' && exit 1
(! git --version || ! gh --version) && >&2 echo 'git or gh not installed' && exit 1

>&2 echo 'Not pushing potential git changes'

# Pull changes from remote or clone if not existing
# Takes the name of a personal repo as an argument
pull_or_clone() {
  local repo=$(echo "$1" | sed 's/\w*\///')
  local giturl="ssh://git@github.com/$1.git"
  (cd "$repo" 2>/dev/null && git pull && cd ..) || git clone $giturl || >&2 echo "Could not backup github repo $1"
}

cd $BACKUP_MOUNT
mkdir -p github
cd github
repos=$(gh repo list | grep -Eo '^\S+/\S+')
for repo in $repos; do
  pull_or_clone $repo
done
