import = ["/home/eric/.config/alacritty/nord.toml"]

[font]
size = 14

[font.normal]
family = "Source Code Pro"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
dynamic_padding = true

[window.padding]
x = 5
y = 5
