#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    at [-o] CONTEXT"
  echo "      Show tasks with a specific context (don't include the @ sign),"
  echo "      or no context at all."
  echo "      -o flag means only show tasks in the specific context."
  echo ""
  exit
}

# turn off footer
TODOTXT_VERBOSE=0

# check if -o flag specified, which means only context
if [ "$1" == "-o" ]; then
  ONLY=1
  shift
fi

# get next tasks with specified context
"$TODO_FULL_SH" command ls "\B@$1\b" +next

# get next tasks without context
if [ -z "$ONLY" ]; then
  "$TODO_FULL_SH" command ls "-\B@\w" +next
fi
