#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    at [context]"
  echo "      Show tasks with a specific context (don't include the @ sign),"
  echo "      or no context at all."
  echo ""
  exit
}

# turn off footer
TODOTXT_VERBOSE=0

# get next tasks with specified context
"$TODO_FULL_SH" command ls "\B@$1\b" +next

# get next tasks without context
"$TODO_FULL_SH" command ls "-\B@\w" +next
