#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    do ITEM#[, ITEM#, ITEM#, ...]"
  echo "      Complete task(s) and check for next steps."
  echo ""
  exit
}

completed="$@"

# list projects
for task_num; do
# find first completed item projects (excl. +next and +wf)
  project=$(sed -n "$task_num"p $TODO_DIR/todo.txt | grep -Eo '\B\+\S+' | grep -Ev '\+next|+wf')
  projects="$projects $project"
done

# complete tasks here to make sure task numbers are right
$TODO_FULL_SH command do $@

source "$(dirname $0)/_getnext.sh"

# go through projects and ask for next tasks
for project in $projects; do
  _getnext $project
done
