#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    weekly"
  echo "      Check for waiting for tasks, projects without next tasks, and"
  echo "      tasks without a project. Act accordingly."
  echo ""
  exit
}

# show waiting for and prompt for done tasks

echo 'WAITING FOR TASKS (step 1/3)'
echo '=========='
echo

$TODO_FULL_SH wf

echo
echo 'Which of these are now done?'
read wf_done
[ -n "$wf_done" ] && $TODO_FULL_SH do $wf_done

# get projects without next task and prompt for (possible) next

echo
echo 'PROJECTS WITHOUT NEXT TASK (step 2/3)'
echo '=========='

regex='\B\+\S+'

all=$(grep -Eo "$regex" "$TODO_DIR/todo.txt" | sort | uniq)
next=$(grep -E '+next|+wf' "$TODO_DIR/todo.txt" | grep -Eo "$regex" | sort | uniq)

nonext=$(comm -3 <(echo "$all") <(echo "$next"))
echo "$nonext"
echo

source "$(dirname $0)/_getnext.sh"

while IFS= read -r project <&3; do
  _getnext $project
done 3<<< "$nonext"

# show tasks without a project (s/m or unprocessed) and loop those with replace

echo 'TASKS WITHOUT A PROJECT (step 3/3)'
echo '=========='
echo
$TODO_FULL_SH process
