#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "    wf"
  echo "      List waiting for actions, i.e. with project +wf"
  echo "      Additional arguments are passed to \`ls\`."
  echo ""
  exit
}

"$TODO_FULL_SH" ls +wf "$@"
