[language-server.deno]
command = "deno"
args = ["lsp"]
config = { enable = true, lint = true, unstable = true }

[[language]]
name = "javascript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = [ "deno" ]
auto-format = true

[[language]]
name = "jsx"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = [ "deno" ]
auto-format = true

[[language]]
name = "typescript"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = [ "deno" ]
auto-format = true

[[language]]
name = "tsx"
shebangs = ["deno", "node"]
roots = ["deno.json", "package.json", "tsconfig.json"]
language-servers = [ "deno" ]
auto-format = true
